### ISSUE TITLE
Include redcap_csrf_token

### ISSUE THREAD

**Issue by vittoriaramella** [lsgs/redcap-locking-api#11]
Hi, 
I'm trying to use the Locking API module but I'm not that API savvy. 

When i use the command 
**curl -d 'token=XXXXXXXXXXXXXXXXXXXX&returnFormat=json&record=101' 'https://redcap.xxxxxxxxxxxx/api/?NOAUTH&type=module&prefix=locking_api&page=status'**
I get the following error:
![image](https://user-images.githubusercontent.com/108271982/205328075-9204101a-9bec-426c-b378-e170aac7183c.png)

How can I pass the redcap_csrf_token as a parameter? I know that the redcap_csrf_token is a nonce, so I was wondering how can I pass it through the POST request.

Thank you in advance, any help would be appreciated!

Best;
Vittoria

**Comment by lsgs** [comment]
@vittoriaramella please check out v2.1.1 of this EM that is available through the REDCap Repo now. This issue should be fixed.
