### ISSUE TITLE
API parameters

### ISSUE THREAD

**Issue by fredmonfardini** [lsgs/redcap-locking-api#12]
Hello,

I'm trying to use this API in REDCap using the R language and I wrote the code below.

I passed the following parameters: URL, Token, action, record and outputs/formats in JSON.

And an additional comment. Before I used this module in version v2.0.1 and it worked.

Now in version v2.1.0, this error is occurring.

Can you tell me which argument is missing?

Thanks. Fred.

```
# Code R

## Input
redcap_uri = ''
token = ""
action = "status"
record= "1"

## Code to POST
base_uri <- httr::parse_url(redcap_uri)

query <- list(
  NOAUTH = ""
  , type = "module"
  , prefix = "locking_api"
  , page = action
)

base_uri$query <- query
arg1 = httr::build_url(base_uri)

arg2 <- list(
  token = token
  , format = "json"
  , returnFormat = "json"
  , lock_record_level = "true"
  , record = jsonlite::toJSON(record)
)

response <- httr::POST(
  url = arg1
  , encode = "form"
  , body = arg2
)

## Output
httr::content(response, type = "application/json")
```
And return this error
```
$error
[1] "An unknown error occurred. Please check your API parameters."
```

**Comment by echaritos** [comment]
We seem to have the same problem.  When executing

`curl -d "token=1F9C31078E617BE2DDF66DAD38ED0E4E&returnFormat=json&record=2988&instrument=reporttexte" "http://192.168.28.111/redcap/api/?NOAUTH&type=module&prefix=locking_api&page=lock&record=2988&lock_record_level=1"
`

we get 

`{"error":"An unknown error occurred. Please check your API parameters."}
`

**Comment by echaritos** [comment]
reverting back to 2.0.1 seems to fix the error

**Comment by lsgs** [comment]
@fredmonfardini, @echaritos please check out v2.1.1 of this EM that is available through the REDCap Repo now. This issue should be fixed.

One other thing @fredmonfardini:  be careful with the data types of the parameters you send. I think you will need to use `, lock_record_level = 1` or `, lock_record_level = true` rather than `, lock_record_level = "true"`.
