### ISSUE TITLE
Unable to get Record Level Lock Status

### ISSUE THREAD

**Issue by jamescogo** [lsgs/redcap-locking-api#13]
Current Environment: REDCap 13.3.1 · PHP 8.0.27 (Linux/Unix OS) · MariaDB 10.3.13 · Locking API - v2.1.1

Running the following code:
`curl -d "token=[##################]&returnFormat=json&record=1&arm=event_1_arm_1&lock_record_level=true" "https://redcap.myworkplace.org/api/?NOAUTH&type=module&prefix=locking_api&page=status"`

Results in the following error:
`<?xml version="1.0" encoding="UTF-8" ?><hash><error>One or more of the supplied records do not exist: </error></hash>`

As a test,  to double check my connectivity, I had ran the following code with no issues:
`curl -d "token=[##################]&returnFormat=json&record=1&event=event_1_arm_1" "https://redcap.myworkplace.org/api/?NOAUTH&type=module&prefix=locking_api&page=status"`

**Comment by lsgs** [comment]
Thank you for reporting the issue @jamescogo. I've done a v2.1.2 release that (along with a couple of other things) addressed one way that error message could be returned. Please reopen if needed.
