### ISSUE TITLE
optional commas

### ISSUE THREAD

**Issue by wibeasley** [lsgs/redcap-locking-api#2]
When I was formatting the documentation in https://github.com/lsgs/redcap-locking-api/pull/1, I noticed three commas might be out of place.  There are three instances of `record[,event][,instrument],[instance]`.

Should the last comma move into the square brackets, so it's `record[,event][,instrument][,instance]`?

**Comment by lsgs** [comment]
Thanks very much @wibeasley. Much appreciated. Is the module working OK for you? If so I'll do a new release with just the readme updates.

**Comment by wibeasley** [comment]
@lsgs, actually I wasn't using it.  I was browsing for something else and saw your name.  I've liked your stuff in the past, so decided to peek at this one.

**Comment by lsgs** [comment]
No worries Will. I did a new release with just the readme improvements.
Thanks again,
Luke

.
________________________________
