### ISSUE TITLE
Is it possible to lock/unlock empty forms/instruments? 

### ISSUE THREAD

**Issue by pdelteil** [lsgs/redcap-locking-api#3]
If so, where should I focus on? 

Thanks.

**Comment by lsgs** [comment]
It should be just like non-empty instruments, @pdelteil. Are you finding different?

**Comment by pdelteil** [comment]
We need to lock and unlock instruments with no data (yet). Just like on redcap.

**Comment by lsgs** [comment]
And are you finding that it is not working then?

**Comment by pdelteil** [comment]
Hi there,

The unlock and lock methods do not work with empty forms
[Image](https://ibb.co/gMSpg0z)

**Comment by lsgs** [comment]
Locking and unlocking of unsaved forms is possible in the new release, @pdelteil. Thanks for highlighting the issue.

**Comment by fredmonfardini** [comment]
Hello, I have the same problem, but I am using a function in R to operate an API.

What are the arguments I have to pass to lock an empty page?
