### ISSUE TITLE
[Feature Request] Lock entire record

### ISSUE THREAD

**Issue by tertek** [lsgs/redcap-locking-api#5]
Currently the API does not support to lock the entire record. Through UI this is possible and needed in some cases:
![image](https://user-images.githubusercontent.com/75415872/107360810-bc527c00-6ad6-11eb-9ddd-5799e5fa507f.png)

A record that is locked entirely does not grant access to add a new repeating instrument. As soon as someone tries to add (mistakenly) a repeating instrument to an entirely locked record it will be blocked:

![image](https://user-images.githubusercontent.com/75415872/107361026-03407180-6ad7-11eb-84ed-e8ebce08cfbc.png)

I have checked how the UI performs this and found in class `Locking->lockWholeRecord()` as the way. It would be easy to add this to the API either as a flag to the lock/unlock endpoints/pages or as a completely new endpoint/page.

I could open a PR since we need this feature very soon.

**Comment by lsgs** [comment]
Thanks very much @tertek . I've merged the PR and made a few further tweaks you'll see. I've done a new release and sent it to Vanderbilt so with luck it'll be available via the official REDCap repo very soon.
