### ISSUE TITLE
Is it possible to query the status, lock or unlock multiple records with one command?

### ISSUE THREAD

**Issue by echaritos** [lsgs/redcap-locking-api#8]
I am using `system(sprintf('curl -d "token=%s&returnFormat=json&record=%s" "http://%s/redcap/api/?NOAUTH&type=module&prefix=locking_api&page=status"', token, record, server)[1])` to lock unlock and query status of records in RedCap. 

Is it possible to lock unlock and query multiple records with one command?

Thanks

**Comment by lsgs** [comment]
You can lock multiple records in a single call using record-level locking (`&lock_record_level=1`) but currently not particular instruments for multiple records in an single call. It would be a worthwhile extension for a future version...
