### ISSUE TITLE
basic status operation

### ISSUE THREAD

**Issue by jthomas08** [lsgs/redcap-locking-api#9]
I’m testing out the locking EM to get the lock status of record 1, but I can’t seem to get lock status. any ideas what I'm missing?

curl -d "token=xxx&record=1arm=1&lock_record_level=true" https://stage-redcap.mdanderson.org/api/?NOAUTH&type=module&prefix=locking_api&page=status

<?xml version="1.0" encoding="UTF-8" ?><hash><error>An unknown error occurred. Please check your API parameters.</error></hash>

**Comment by lsgs** [comment]
Probably too late, sorry @jthomas08. It looks like you're missing the `&` between the record id and `arm`.
